//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebServiceGameCenterSoap", Namespace="http://tempuri.org/")]
public partial class WebServiceGameCenter : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback VerifyCredentialsOperationCompleted;
    
    private System.Threading.SendOrPostCallback VerifyCredentialsJavaOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetSelectedEntityDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetErrorMessageOperationCompleted;
    
    private System.Threading.SendOrPostCallback TryErrorHandlingOperationCompleted;
    
    /// <remarks/>
    public WebServiceGameCenter() {
        this.Url = "http://localhost/WebApplicationGameCenter/WebServiceGameCenter.asmx";
    }
    
    /// <remarks/>
    public event VerifyCredentialsCompletedEventHandler VerifyCredentialsCompleted;
    
    /// <remarks/>
    public event VerifyCredentialsJavaCompletedEventHandler VerifyCredentialsJavaCompleted;
    
    /// <remarks/>
    public event GetSelectedEntityDataCompletedEventHandler GetSelectedEntityDataCompleted;
    
    /// <remarks/>
    public event CreateCompletedEventHandler CreateCompleted;
    
    /// <remarks/>
    public event DeleteCompletedEventHandler DeleteCompleted;
    
    /// <remarks/>
    public event GetErrorMessageCompletedEventHandler GetErrorMessageCompleted;
    
    /// <remarks/>
    public event TryErrorHandlingCompletedEventHandler TryErrorHandlingCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyCredentials", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool VerifyCredentials(string id, string loginPassword, out string role) {
        object[] results = this.Invoke("VerifyCredentials", new object[] {
                    id,
                    loginPassword});
        role = ((string)(results[1]));
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginVerifyCredentials(string id, string loginPassword, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("VerifyCredentials", new object[] {
                    id,
                    loginPassword}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndVerifyCredentials(System.IAsyncResult asyncResult, out string role) {
        object[] results = this.EndInvoke(asyncResult);
        role = ((string)(results[1]));
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void VerifyCredentialsAsync(string id, string loginPassword) {
        this.VerifyCredentialsAsync(id, loginPassword, null);
    }
    
    /// <remarks/>
    public void VerifyCredentialsAsync(string id, string loginPassword, object userState) {
        if ((this.VerifyCredentialsOperationCompleted == null)) {
            this.VerifyCredentialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyCredentialsOperationCompleted);
        }
        this.InvokeAsync("VerifyCredentials", new object[] {
                    id,
                    loginPassword}, this.VerifyCredentialsOperationCompleted, userState);
    }
    
    private void OnVerifyCredentialsOperationCompleted(object arg) {
        if ((this.VerifyCredentialsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.VerifyCredentialsCompleted(this, new VerifyCredentialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyCredentialsJava", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string VerifyCredentialsJava(string id, string loginPassword) {
        object[] results = this.Invoke("VerifyCredentialsJava", new object[] {
                    id,
                    loginPassword});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginVerifyCredentialsJava(string id, string loginPassword, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("VerifyCredentialsJava", new object[] {
                    id,
                    loginPassword}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndVerifyCredentialsJava(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void VerifyCredentialsJavaAsync(string id, string loginPassword) {
        this.VerifyCredentialsJavaAsync(id, loginPassword, null);
    }
    
    /// <remarks/>
    public void VerifyCredentialsJavaAsync(string id, string loginPassword, object userState) {
        if ((this.VerifyCredentialsJavaOperationCompleted == null)) {
            this.VerifyCredentialsJavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyCredentialsJavaOperationCompleted);
        }
        this.InvokeAsync("VerifyCredentialsJava", new object[] {
                    id,
                    loginPassword}, this.VerifyCredentialsJavaOperationCompleted, userState);
    }
    
    private void OnVerifyCredentialsJavaOperationCompleted(object arg) {
        if ((this.VerifyCredentialsJavaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.VerifyCredentialsJavaCompleted(this, new VerifyCredentialsJavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSelectedEntityData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetSelectedEntityData(string selectedEntityCon, string role) {
        object[] results = this.Invoke("GetSelectedEntityData", new object[] {
                    selectedEntityCon,
                    role});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetSelectedEntityData(string selectedEntityCon, string role, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetSelectedEntityData", new object[] {
                    selectedEntityCon,
                    role}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetSelectedEntityData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetSelectedEntityDataAsync(string selectedEntityCon, string role) {
        this.GetSelectedEntityDataAsync(selectedEntityCon, role, null);
    }
    
    /// <remarks/>
    public void GetSelectedEntityDataAsync(string selectedEntityCon, string role, object userState) {
        if ((this.GetSelectedEntityDataOperationCompleted == null)) {
            this.GetSelectedEntityDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSelectedEntityDataOperationCompleted);
        }
        this.InvokeAsync("GetSelectedEntityData", new object[] {
                    selectedEntityCon,
                    role}, this.GetSelectedEntityDataOperationCompleted, userState);
    }
    
    private void OnGetSelectedEntityDataOperationCompleted(object arg) {
        if ((this.GetSelectedEntityDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetSelectedEntityDataCompleted(this, new GetSelectedEntityDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Create", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool Create(KeyValuePairCustom[] entityData, string selectedEntityCon, string role) {
        object[] results = this.Invoke("Create", new object[] {
                    entityData,
                    selectedEntityCon,
                    role});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreate(KeyValuePairCustom[] entityData, string selectedEntityCon, string role, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Create", new object[] {
                    entityData,
                    selectedEntityCon,
                    role}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndCreate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void CreateAsync(KeyValuePairCustom[] entityData, string selectedEntityCon, string role) {
        this.CreateAsync(entityData, selectedEntityCon, role, null);
    }
    
    /// <remarks/>
    public void CreateAsync(KeyValuePairCustom[] entityData, string selectedEntityCon, string role, object userState) {
        if ((this.CreateOperationCompleted == null)) {
            this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
        }
        this.InvokeAsync("Create", new object[] {
                    entityData,
                    selectedEntityCon,
                    role}, this.CreateOperationCompleted, userState);
    }
    
    private void OnCreateOperationCompleted(object arg) {
        if ((this.CreateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool Delete(string idDelete, string selectedEntityCon, string role) {
        object[] results = this.Invoke("Delete", new object[] {
                    idDelete,
                    selectedEntityCon,
                    role});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDelete(string idDelete, string selectedEntityCon, string role, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Delete", new object[] {
                    idDelete,
                    selectedEntityCon,
                    role}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndDelete(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteAsync(string idDelete, string selectedEntityCon, string role) {
        this.DeleteAsync(idDelete, selectedEntityCon, role, null);
    }
    
    /// <remarks/>
    public void DeleteAsync(string idDelete, string selectedEntityCon, string role, object userState) {
        if ((this.DeleteOperationCompleted == null)) {
            this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
        }
        this.InvokeAsync("Delete", new object[] {
                    idDelete,
                    selectedEntityCon,
                    role}, this.DeleteOperationCompleted, userState);
    }
    
    private void OnDeleteOperationCompleted(object arg) {
        if ((this.DeleteCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetErrorMessage() {
        object[] results = this.Invoke("GetErrorMessage", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetErrorMessage(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetErrorMessage", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetErrorMessage(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetErrorMessageAsync() {
        this.GetErrorMessageAsync(null);
    }
    
    /// <remarks/>
    public void GetErrorMessageAsync(object userState) {
        if ((this.GetErrorMessageOperationCompleted == null)) {
            this.GetErrorMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorMessageOperationCompleted);
        }
        this.InvokeAsync("GetErrorMessage", new object[0], this.GetErrorMessageOperationCompleted, userState);
    }
    
    private void OnGetErrorMessageOperationCompleted(object arg) {
        if ((this.GetErrorMessageCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetErrorMessageCompleted(this, new GetErrorMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TryErrorHandling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string TryErrorHandling() {
        object[] results = this.Invoke("TryErrorHandling", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginTryErrorHandling(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("TryErrorHandling", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndTryErrorHandling(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void TryErrorHandlingAsync() {
        this.TryErrorHandlingAsync(null);
    }
    
    /// <remarks/>
    public void TryErrorHandlingAsync(object userState) {
        if ((this.TryErrorHandlingOperationCompleted == null)) {
            this.TryErrorHandlingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTryErrorHandlingOperationCompleted);
        }
        this.InvokeAsync("TryErrorHandling", new object[0], this.TryErrorHandlingOperationCompleted, userState);
    }
    
    private void OnTryErrorHandlingOperationCompleted(object arg) {
        if ((this.TryErrorHandlingCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.TryErrorHandlingCompleted(this, new TryErrorHandlingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class KeyValuePairCustom {
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void VerifyCredentialsCompletedEventHandler(object sender, VerifyCredentialsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VerifyCredentialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal VerifyCredentialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public string role {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void VerifyCredentialsJavaCompletedEventHandler(object sender, VerifyCredentialsJavaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VerifyCredentialsJavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal VerifyCredentialsJavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetSelectedEntityDataCompletedEventHandler(object sender, GetSelectedEntityDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetSelectedEntityDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetSelectedEntityDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetErrorMessageCompletedEventHandler(object sender, GetErrorMessageCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetErrorMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetErrorMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void TryErrorHandlingCompletedEventHandler(object sender, TryErrorHandlingCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TryErrorHandlingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal TryErrorHandlingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
